FROM golang:1.25 as build

WORKDIR /go/src/app

COPY agent/go.mod agent/go.sum /go/src/app
COPY schema/go.mod schema/go.sum /go/src/schema

RUN go mod download

COPY agent /go/src/app
COPY schema /go/src/schema

RUN go vet -v
RUN go test -v

RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /go/bin/app /
CMD ["/app"]
