// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: agent_api.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Port          *uint32                `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	Protocol      *string                `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_agent_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{0}
}

func (x *PortSpec) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PortSpec) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *PortSpec) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

type ServiceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   *string                `protobuf:"bytes,1,req,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Instance      *string                `protobuf:"bytes,2,req,name=instance" json:"instance,omitempty"`
	Location      *string                `protobuf:"bytes,3,req,name=location" json:"location,omitempty"`
	Datacenter    *string                `protobuf:"bytes,4,req,name=datacenter" json:"datacenter,omitempty"`
	Node          *string                `protobuf:"bytes,5,req,name=node" json:"node,omitempty"`
	Addresses     []string               `protobuf:"bytes,6,rep,name=addresses" json:"addresses,omitempty"`
	Ports         []*PortSpec            `protobuf:"bytes,7,rep,name=ports" json:"ports,omitempty"`
	MetricsPort   *uint32                `protobuf:"varint,8,opt,name=metrics_port,json=metricsPort" json:"metrics_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSpec) Reset() {
	*x = ServiceSpec{}
	mi := &file_agent_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpec) ProtoMessage() {}

func (x *ServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpec.ProtoReflect.Descriptor instead.
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceSpec) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *ServiceSpec) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *ServiceSpec) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *ServiceSpec) GetDatacenter() string {
	if x != nil && x.Datacenter != nil {
		return *x.Datacenter
	}
	return ""
}

func (x *ServiceSpec) GetNode() string {
	if x != nil && x.Node != nil {
		return *x.Node
	}
	return ""
}

func (x *ServiceSpec) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ServiceSpec) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceSpec) GetMetricsPort() uint32 {
	if x != nil && x.MetricsPort != nil {
		return *x.MetricsPort
	}
	return 0
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *string                `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Location      *string                `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Datacenter    *string                `protobuf:"bytes,3,opt,name=datacenter" json:"datacenter,omitempty"`
	Node          *string                `protobuf:"bytes,4,opt,name=node" json:"node,omitempty"`
	Instance      *string                `protobuf:"bytes,5,opt,name=instance" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_agent_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *DiscoverRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *DiscoverRequest) GetDatacenter() string {
	if x != nil && x.Datacenter != nil {
		return *x.Datacenter
	}
	return ""
}

func (x *DiscoverRequest) GetNode() string {
	if x != nil && x.Node != nil {
		return *x.Node
	}
	return ""
}

func (x *DiscoverRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceSpec         `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_agent_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverResponse) GetServices() []*ServiceSpec {
	if x != nil {
		return x.Services
	}
	return nil
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *string                `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Instance      *string                `protobuf:"bytes,2,req,name=instance" json:"instance,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses" json:"addresses,omitempty"`
	Ports         []*PortSpec            `protobuf:"bytes,4,rep,name=ports" json:"ports,omitempty"`
	MetricsPort   *uint32                `protobuf:"varint,5,opt,name=metrics_port,json=metricsPort" json:"metrics_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_agent_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterServiceRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *RegisterServiceRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *RegisterServiceRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *RegisterServiceRequest) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *RegisterServiceRequest) GetMetricsPort() uint32 {
	if x != nil && x.MetricsPort != nil {
		return *x.MetricsPort
	}
	return 0
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceSpec           `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_agent_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterServiceResponse) GetService() *ServiceSpec {
	if x != nil {
		return x.Service
	}
	return nil
}

type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *string                `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Instance      *string                `protobuf:"bytes,2,req,name=instance" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_agent_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterServiceRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *DeregisterServiceRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

type DeregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceResponse) Reset() {
	*x = DeregisterServiceResponse{}
	mi := &file_agent_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceResponse) ProtoMessage() {}

func (x *DeregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{7}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{8}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{9}
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_agent_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{10}
}

type ConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Certificate     []byte                 `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Key             []byte                 `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	HeartbeatPeriod *uint32                `protobuf:"varint,3,req,name=heartbeat_period,json=heartbeatPeriod" json:"heartbeat_period,omitempty"`
	RenewPeriod     *uint64                `protobuf:"varint,4,req,name=renew_period,json=renewPeriod" json:"renew_period,omitempty"`
	RegistryAddrs   []string               `protobuf:"bytes,5,rep,name=registry_addrs,json=registryAddrs" json:"registry_addrs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_agent_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *ConfigResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ConfigResponse) GetHeartbeatPeriod() uint32 {
	if x != nil && x.HeartbeatPeriod != nil {
		return *x.HeartbeatPeriod
	}
	return 0
}

func (x *ConfigResponse) GetRenewPeriod() uint64 {
	if x != nil && x.RenewPeriod != nil {
		return *x.RenewPeriod
	}
	return 0
}

func (x *ConfigResponse) GetRegistryAddrs() []string {
	if x != nil {
		return x.RegistryAddrs
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_agent_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{12}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_agent_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_rawDescGZIP(), []int{13}
}

var File_agent_api_proto protoreflect.FileDescriptor

const file_agent_api_proto_rawDesc = "" +
	"\n" +
	"\x0fagent_api.proto\"N\n" +
	"\bPortSpec\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x02(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xfe\x01\n" +
	"\vServiceSpec\x12!\n" +
	"\fservice_name\x18\x01 \x02(\tR\vserviceName\x12\x1a\n" +
	"\binstance\x18\x02 \x02(\tR\binstance\x12\x1a\n" +
	"\blocation\x18\x03 \x02(\tR\blocation\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x04 \x02(\tR\n" +
	"datacenter\x12\x12\n" +
	"\x04node\x18\x05 \x02(\tR\x04node\x12\x1c\n" +
	"\taddresses\x18\x06 \x03(\tR\taddresses\x12\x1f\n" +
	"\x05ports\x18\a \x03(\v2\t.PortSpecR\x05ports\x12!\n" +
	"\fmetrics_port\x18\b \x01(\rR\vmetricsPort\"\x97\x01\n" +
	"\x0fDiscoverRequest\x12\x18\n" +
	"\aservice\x18\x01 \x02(\tR\aservice\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x03 \x01(\tR\n" +
	"datacenter\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12\x1a\n" +
	"\binstance\x18\x05 \x01(\tR\binstance\"<\n" +
	"\x10DiscoverResponse\x12(\n" +
	"\bservices\x18\x01 \x03(\v2\f.ServiceSpecR\bservices\"\xb0\x01\n" +
	"\x16RegisterServiceRequest\x12\x18\n" +
	"\aservice\x18\x01 \x02(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x02 \x02(\tR\binstance\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x1f\n" +
	"\x05ports\x18\x04 \x03(\v2\t.PortSpecR\x05ports\x12!\n" +
	"\fmetrics_port\x18\x05 \x01(\rR\vmetricsPort\"A\n" +
	"\x17RegisterServiceResponse\x12&\n" +
	"\aservice\x18\x01 \x02(\v2\f.ServiceSpecR\aservice\"P\n" +
	"\x18DeregisterServiceRequest\x12\x18\n" +
	"\aservice\x18\x01 \x02(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x02 \x02(\tR\binstance\"\x1b\n" +
	"\x19DeregisterServiceResponse\"\x12\n" +
	"\x10HeartbeatRequest\"\x13\n" +
	"\x11HeartbeatResponse\"\x0f\n" +
	"\rConfigRequest\"\xb9\x01\n" +
	"\x0eConfigResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12)\n" +
	"\x10heartbeat_period\x18\x03 \x02(\rR\x0fheartbeatPeriod\x12!\n" +
	"\frenew_period\x18\x04 \x02(\x04R\vrenewPeriod\x12%\n" +
	"\x0eregistry_addrs\x18\x05 \x03(\tR\rregistryAddrs\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse2\xd2\x02\n" +
	"\bAgentAPI\x121\n" +
	"\bDiscover\x12\x10.DiscoverRequest\x1a\x11.DiscoverResponse\"\x00\x12?\n" +
	"\bRegister\x12\x17.RegisterServiceRequest\x1a\x18.RegisterServiceResponse\"\x00\x12E\n" +
	"\n" +
	"Deregister\x12\x19.DeregisterServiceRequest\x1a\x1a.DeregisterServiceResponse\"\x00\x124\n" +
	"\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\"\x00\x12+\n" +
	"\x06Config\x12\x0e.ConfigRequest\x1a\x0f.ConfigResponse\"\x00\x12(\n" +
	"\x05Reset\x12\r.ResetRequest\x1a\x0e.ResetResponse\"\x00B\x0fZ\rssle/services"

var (
	file_agent_api_proto_rawDescOnce sync.Once
	file_agent_api_proto_rawDescData []byte
)

func file_agent_api_proto_rawDescGZIP() []byte {
	file_agent_api_proto_rawDescOnce.Do(func() {
		file_agent_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_api_proto_rawDesc), len(file_agent_api_proto_rawDesc)))
	})
	return file_agent_api_proto_rawDescData
}

var file_agent_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_api_proto_goTypes = []any{
	(*PortSpec)(nil),                  // 0: PortSpec
	(*ServiceSpec)(nil),               // 1: ServiceSpec
	(*DiscoverRequest)(nil),           // 2: DiscoverRequest
	(*DiscoverResponse)(nil),          // 3: DiscoverResponse
	(*RegisterServiceRequest)(nil),    // 4: RegisterServiceRequest
	(*RegisterServiceResponse)(nil),   // 5: RegisterServiceResponse
	(*DeregisterServiceRequest)(nil),  // 6: DeregisterServiceRequest
	(*DeregisterServiceResponse)(nil), // 7: DeregisterServiceResponse
	(*HeartbeatRequest)(nil),          // 8: HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 9: HeartbeatResponse
	(*ConfigRequest)(nil),             // 10: ConfigRequest
	(*ConfigResponse)(nil),            // 11: ConfigResponse
	(*ResetRequest)(nil),              // 12: ResetRequest
	(*ResetResponse)(nil),             // 13: ResetResponse
}
var file_agent_api_proto_depIdxs = []int32{
	0,  // 0: ServiceSpec.ports:type_name -> PortSpec
	1,  // 1: DiscoverResponse.services:type_name -> ServiceSpec
	0,  // 2: RegisterServiceRequest.ports:type_name -> PortSpec
	1,  // 3: RegisterServiceResponse.service:type_name -> ServiceSpec
	2,  // 4: AgentAPI.Discover:input_type -> DiscoverRequest
	4,  // 5: AgentAPI.Register:input_type -> RegisterServiceRequest
	6,  // 6: AgentAPI.Deregister:input_type -> DeregisterServiceRequest
	8,  // 7: AgentAPI.Heartbeat:input_type -> HeartbeatRequest
	10, // 8: AgentAPI.Config:input_type -> ConfigRequest
	12, // 9: AgentAPI.Reset:input_type -> ResetRequest
	3,  // 10: AgentAPI.Discover:output_type -> DiscoverResponse
	5,  // 11: AgentAPI.Register:output_type -> RegisterServiceResponse
	7,  // 12: AgentAPI.Deregister:output_type -> DeregisterServiceResponse
	9,  // 13: AgentAPI.Heartbeat:output_type -> HeartbeatResponse
	11, // 14: AgentAPI.Config:output_type -> ConfigResponse
	13, // 15: AgentAPI.Reset:output_type -> ResetResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_api_proto_init() }
func file_agent_api_proto_init() {
	if File_agent_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_api_proto_rawDesc), len(file_agent_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_api_proto_goTypes,
		DependencyIndexes: file_agent_api_proto_depIdxs,
		MessageInfos:      file_agent_api_proto_msgTypes,
	}.Build()
	File_agent_api_proto = out.File
	file_agent_api_proto_goTypes = nil
	file_agent_api_proto_depIdxs = nil
}
