// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: peer_api.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerAPI_GetPeers_FullMethodName           = "/PeerAPI/GetPeers"
	PeerAPI_AddSelfPeer_FullMethodName        = "/PeerAPI/AddSelfPeer"
	PeerAPI_AddNode_FullMethodName            = "/PeerAPI/AddNode"
	PeerAPI_GetNodeCredentials_FullMethodName = "/PeerAPI/GetNodeCredentials"
)

// PeerAPIClient is the client API for PeerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerAPIClient interface {
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	AddSelfPeer(ctx context.Context, in *AddSelfPeerRequest, opts ...grpc.CallOption) (*AddSelfPeerResponse, error)
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*AddNodeResponse, error)
	GetNodeCredentials(ctx context.Context, in *GetNodeCredentialsRequest, opts ...grpc.CallOption) (*GetNodeCredentialsResponse, error)
}

type peerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerAPIClient(cc grpc.ClientConnInterface) PeerAPIClient {
	return &peerAPIClient{cc}
}

func (c *peerAPIClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, PeerAPI_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerAPIClient) AddSelfPeer(ctx context.Context, in *AddSelfPeerRequest, opts ...grpc.CallOption) (*AddSelfPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSelfPeerResponse)
	err := c.cc.Invoke(ctx, PeerAPI_AddSelfPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerAPIClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*AddNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNodeResponse)
	err := c.cc.Invoke(ctx, PeerAPI_AddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerAPIClient) GetNodeCredentials(ctx context.Context, in *GetNodeCredentialsRequest, opts ...grpc.CallOption) (*GetNodeCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeCredentialsResponse)
	err := c.cc.Invoke(ctx, PeerAPI_GetNodeCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerAPIServer is the server API for PeerAPI service.
// All implementations must embed UnimplementedPeerAPIServer
// for forward compatibility.
type PeerAPIServer interface {
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	AddSelfPeer(context.Context, *AddSelfPeerRequest) (*AddSelfPeerResponse, error)
	AddNode(context.Context, *AddNodeRequest) (*AddNodeResponse, error)
	GetNodeCredentials(context.Context, *GetNodeCredentialsRequest) (*GetNodeCredentialsResponse, error)
	mustEmbedUnimplementedPeerAPIServer()
}

// UnimplementedPeerAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerAPIServer struct{}

func (UnimplementedPeerAPIServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedPeerAPIServer) AddSelfPeer(context.Context, *AddSelfPeerRequest) (*AddSelfPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSelfPeer not implemented")
}
func (UnimplementedPeerAPIServer) AddNode(context.Context, *AddNodeRequest) (*AddNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNode not implemented")
}
func (UnimplementedPeerAPIServer) GetNodeCredentials(context.Context, *GetNodeCredentialsRequest) (*GetNodeCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeCredentials not implemented")
}
func (UnimplementedPeerAPIServer) mustEmbedUnimplementedPeerAPIServer() {}
func (UnimplementedPeerAPIServer) testEmbeddedByValue()                 {}

// UnsafePeerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerAPIServer will
// result in compilation errors.
type UnsafePeerAPIServer interface {
	mustEmbedUnimplementedPeerAPIServer()
}

func RegisterPeerAPIServer(s grpc.ServiceRegistrar, srv PeerAPIServer) {
	// If the following call panics, it indicates UnimplementedPeerAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerAPI_ServiceDesc, srv)
}

func _PeerAPI_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerAPIServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerAPI_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerAPIServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerAPI_AddSelfPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSelfPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerAPIServer).AddSelfPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerAPI_AddSelfPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerAPIServer).AddSelfPeer(ctx, req.(*AddSelfPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerAPI_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerAPIServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerAPI_AddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerAPIServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerAPI_GetNodeCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerAPIServer).GetNodeCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerAPI_GetNodeCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerAPIServer).GetNodeCredentials(ctx, req.(*GetNodeCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerAPI_ServiceDesc is the grpc.ServiceDesc for PeerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PeerAPI",
	HandlerType: (*PeerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeers",
			Handler:    _PeerAPI_GetPeers_Handler,
		},
		{
			MethodName: "AddSelfPeer",
			Handler:    _PeerAPI_AddSelfPeer_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _PeerAPI_AddNode_Handler,
		},
		{
			MethodName: "GetNodeCredentials",
			Handler:    _PeerAPI_GetNodeCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peer_api.proto",
}
