// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: peer_api.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	PeerUrls      []string               `protobuf:"bytes,3,rep,name=peer_urls,json=peerUrls" json:"peer_urls,omitempty"`
	ClientUrls    []string               `protobuf:"bytes,4,rep,name=client_urls,json=clientUrls" json:"client_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_peer_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Peer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Peer) GetPeerUrls() []string {
	if x != nil {
		return x.PeerUrls
	}
	return nil
}

func (x *Peer) GetClientUrls() []string {
	if x != nil {
		return x.ClientUrls
	}
	return nil
}

type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_peer_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{1}
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_peer_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type AddSelfPeerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdvertisedUrls []string               `protobuf:"bytes,1,rep,name=advertised_urls,json=advertisedUrls" json:"advertised_urls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddSelfPeerRequest) Reset() {
	*x = AddSelfPeerRequest{}
	mi := &file_peer_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSelfPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSelfPeerRequest) ProtoMessage() {}

func (x *AddSelfPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSelfPeerRequest.ProtoReflect.Descriptor instead.
func (*AddSelfPeerRequest) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddSelfPeerRequest) GetAdvertisedUrls() []string {
	if x != nil {
		return x.AdvertisedUrls
	}
	return nil
}

type AddSelfPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSelfPeerResponse) Reset() {
	*x = AddSelfPeerResponse{}
	mi := &file_peer_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSelfPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSelfPeerResponse) ProtoMessage() {}

func (x *AddSelfPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSelfPeerResponse.ProtoReflect.Descriptor instead.
func (*AddSelfPeerResponse) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{4}
}

type AddAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Datacenter    *string                `protobuf:"bytes,2,req,name=datacenter" json:"datacenter,omitempty"`
	Location      *string                `protobuf:"bytes,3,req,name=location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentRequest) Reset() {
	*x = AddAgentRequest{}
	mi := &file_peer_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentRequest) ProtoMessage() {}

func (x *AddAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentRequest.ProtoReflect.Descriptor instead.
func (*AddAgentRequest) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddAgentRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AddAgentRequest) GetDatacenter() string {
	if x != nil && x.Datacenter != nil {
		return *x.Datacenter
	}
	return ""
}

func (x *AddAgentRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

type AddAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,req,name=certificate" json:"certificate,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentResponse) Reset() {
	*x = AddAgentResponse{}
	mi := &file_peer_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentResponse) ProtoMessage() {}

func (x *AddAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentResponse.ProtoReflect.Descriptor instead.
func (*AddAgentResponse) Descriptor() ([]byte, []int) {
	return file_peer_api_proto_rawDescGZIP(), []int{6}
}

func (x *AddAgentResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *AddAgentResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_peer_api_proto protoreflect.FileDescriptor

const file_peer_api_proto_rawDesc = "" +
	"\n" +
	"\x0epeer_api.proto\"h\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x1b\n" +
	"\tpeer_urls\x18\x03 \x03(\tR\bpeerUrls\x12\x1f\n" +
	"\vclient_urls\x18\x04 \x03(\tR\n" +
	"clientUrls\"\x11\n" +
	"\x0fGetPeersRequest\"/\n" +
	"\x10GetPeersResponse\x12\x1b\n" +
	"\x05peers\x18\x01 \x03(\v2\x05.PeerR\x05peers\"=\n" +
	"\x12AddSelfPeerRequest\x12'\n" +
	"\x0fadvertised_urls\x18\x01 \x03(\tR\x0eadvertisedUrls\"\x15\n" +
	"\x13AddSelfPeerResponse\"a\n" +
	"\x0fAddAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x02 \x02(\tR\n" +
	"datacenter\x12\x1a\n" +
	"\blocation\x18\x03 \x02(\tR\blocation\"F\n" +
	"\x10AddAgentResponse\x12 \n" +
	"\vcertificate\x18\x01 \x02(\fR\vcertificate\x12\x10\n" +
	"\x03key\x18\x02 \x02(\fR\x03key2\xab\x01\n" +
	"\aPeerAPI\x121\n" +
	"\bGetPeers\x12\x10.GetPeersRequest\x1a\x11.GetPeersResponse\"\x00\x12:\n" +
	"\vAddSelfPeer\x12\x13.AddSelfPeerRequest\x1a\x14.AddSelfPeerResponse\"\x00\x121\n" +
	"\bAddAgent\x12\x10.AddAgentRequest\x1a\x11.AddAgentResponse\"\x00B\x0fZ\rssle/services"

var (
	file_peer_api_proto_rawDescOnce sync.Once
	file_peer_api_proto_rawDescData []byte
)

func file_peer_api_proto_rawDescGZIP() []byte {
	file_peer_api_proto_rawDescOnce.Do(func() {
		file_peer_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_api_proto_rawDesc), len(file_peer_api_proto_rawDesc)))
	})
	return file_peer_api_proto_rawDescData
}

var file_peer_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_peer_api_proto_goTypes = []any{
	(*Peer)(nil),                // 0: Peer
	(*GetPeersRequest)(nil),     // 1: GetPeersRequest
	(*GetPeersResponse)(nil),    // 2: GetPeersResponse
	(*AddSelfPeerRequest)(nil),  // 3: AddSelfPeerRequest
	(*AddSelfPeerResponse)(nil), // 4: AddSelfPeerResponse
	(*AddAgentRequest)(nil),     // 5: AddAgentRequest
	(*AddAgentResponse)(nil),    // 6: AddAgentResponse
}
var file_peer_api_proto_depIdxs = []int32{
	0, // 0: GetPeersResponse.peers:type_name -> Peer
	1, // 1: PeerAPI.GetPeers:input_type -> GetPeersRequest
	3, // 2: PeerAPI.AddSelfPeer:input_type -> AddSelfPeerRequest
	5, // 3: PeerAPI.AddAgent:input_type -> AddAgentRequest
	2, // 4: PeerAPI.GetPeers:output_type -> GetPeersResponse
	4, // 5: PeerAPI.AddSelfPeer:output_type -> AddSelfPeerResponse
	6, // 6: PeerAPI.AddAgent:output_type -> AddAgentResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peer_api_proto_init() }
func file_peer_api_proto_init() {
	if File_peer_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_api_proto_rawDesc), len(file_peer_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_api_proto_goTypes,
		DependencyIndexes: file_peer_api_proto_depIdxs,
		MessageInfos:      file_peer_api_proto_msgTypes,
	}.Build()
	File_peer_api_proto = out.File
	file_peer_api_proto_goTypes = nil
	file_peer_api_proto_depIdxs = nil
}
