name: wordpress-stack
services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    dns: 172.17.0.1
    labels:
      manager: ssle
      ssle.service: mariadb
      ssle.metrics: 9104
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - "3306:3306"
      - "33060:33060"

  exporter:
    image: prom/mysqld-exporter:latest
    command: '--web.telemetry-path=/metrics --mysqld.address=db:3306 --mysqld.username=root'
    dns: 172.17.0.1
    restart: always
    environment:
      - MYSQLD_EXPORTER_PASSWORD=somewordpress
    ports:
      - "9104:9104"

volumes:
  db_data:
