services:
  agent:
    image: "ghcr.io/jcapucho/ssle/agent:latest"
    restart: always
    environment:
      AGENT_JOIN_URL: 10.255.255.15:2383
      AGENT_CA_FILE: /run/secrets/ca-crt
      AGENT_CERTIFICATE: /run/secrets/node-crt
      AGENT_KEY: /run/secrets/node-key
      AGENT_DNS_BIND_ADDR: 0.0.0.0
    ports:
      - 172.17.0.1:53:53/udp
    secrets:
      - ca-crt
      - node-crt
      - node-key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  exporter:
    image: "quay.io/prometheus/node-exporter:latest"
    command: "--path.rootfs=/host"
    pid: "host"
    restart: always
    network_mode: host
    labels:
      manager: ssle
      ssle.service: node
      ssle.metrics: 9100
    ports:
      - 9100:9100
    volumes:
      - /:/host:ro,rslave
    
secrets:
  ca-crt:
    file: ./certs/ca.crt
  node-crt:
    file: ./certs/node.crt
  node-key:
    file: ./certs/node.key
